//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchData
    {
        public int DataID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public Nullable<int> RecordID { get; set; }
        public string ImageName { get; set; }
        public Nullable<int> SpentTime { get; set; }
        public Nullable<System.DateTime> CompleteTime { get; set; }
        public string Data { get; set; }
    }
}
