//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int ConfigID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> FieldNum { get; set; }
        public string MaxChar { get; set; }
        public string CheckBox { get; set; }
        public string FieldNote { get; set; }
        public string Alpha { get; set; }
        public string Num { get; set; }
        public string Dot { get; set; }
        public string Special { get; set; }
        public string Custom { get; set; }
        public string Abbr { get; set; }
        public string FullView { get; set; }
        public string FieldView { get; set; }
        public string FieldName { get; set; }
    }
}
